version: "3.9"

services:
  flask-app:
    image: ghcr.io/erickweyunga/flask-app:latest
    networks:
      - traefik-public
    environment:
      - FLASK_ENV=production
    deploy:
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.flask-app.rule=Host(`flask-app.cloud.erickweyunga.me`)"
        - "traefik.http.services.flask-app.loadbalancer.server.port=5000"

networks:
  traefik-public:
    external: true
